#spring.application.name=chat-app-backend
#
#spring.data.mongodb.uri=mongodb://localhost:27017/chatapp
spring:
  application:
    name: chat-app-backend
  datasource:
    url: "jdbc:mysql://localhost:3306/chat"
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true